server.port: 9090

flyway.baseline-on-migrate: true

spring.application.name: employee-service

zuul.auth.path: http://localhost:9094/auth/auth

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employee?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    time-zone: UTC



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/