server.port : 9090

flyway.baseline-on-migrate : true

spring.application.name : employee-service

zuul:
  auth:
    path: http://apiGateway:9094/auth/auth

spring:
  datasource:
    url: jdbc:mysql://database:3306/employee?useSSL=false&allowPublicKeyRetrieval=true
    username : root
    password : password
  jpa :
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    time-zone : UTC



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://serviceDiscovery:8761/eureka}